version: "3.8"

services:
  frontend:
    image: your-registry/admin-dashboard-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - app-network

  backend:
    image: your-registry/admin-dashboard-backend:latest
    ports:
      - "5000:5000"
    env_file:
      - ./admin-backend/.env
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/admin-dashboard
      - JWT_SECRET=your-production-jwt-secret
      - JWT_EXPIRES_IN=24h
    restart: unless-stopped
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
